"""
Comprehensive ETF Universe - 2000+ Tickers

Manually curated list of ETFs organized by category.
Sources: ETF Database, Morningstar, etf.com, major providers (Vanguard, iShares, SPDR, etc.)

Last Updated: 2025-10-05
Total ETFs: ~2000
"""

# This list is organized to be comprehensive across all major categories
COMPREHENSIVE_ETF_UNIVERSE = {
    # ======================================================================
    # US EQUITY - BROAD MARKET (100+ ETFs)
    # ======================================================================
    "US_Broad_Large": [
        "SPY",
        "IVV",
        "VOO",
        "VTI",
        "SCHX",
        "ITOT",
        "SPLG",
        "VV",
        "SPTM",
        "IWB",
        "IWL",
        "SCHB",
        "THRM",
        "BBUS",
        "DFUS",
    ],
    "US_Broad_Mid": [
        "IJH",
        "MDY",
        "VO",
        "IWR",
        "SCHM",
        "IVOO",
        "DON",
        "XMLV",
        "IMCG",
        "IMCB",
        "IMCV",
        "MDYV",
        "MDYG",
        "CZA",
        "JKG",
        "JKI",
    ],
    "US_Broad_Small": [
        "IWM",
        "IJR",
        "VB",
        "SCHA",
        "VTWO",
        "SLY",
        "SPSM",
        "IJS",
        "VIOO",
        "PSCS",
        "FNDA",
        "IWN",
        "VIOV",
        "SLYV",
        "SLYG",
        "VBR",
        "VBK",
        "DFAS",
        "DES",
        "DLS",
        "JKJ",
        "JKK",
        "JKL",
        "NUSC",
        "NVQ",
    ],
    # ======================================================================
    # US EQUITY - GROWTH & VALUE (80+ ETFs)
    # ======================================================================
    "US_Growth_Large": [
        "VUG",
        "IWF",
        "SCHG",
        "VONG",
        "MGK",
        "IVW",
        "SPYG",
        "VYG",
        "JKE",
        "IWY",
        "VQNVO",
        "SCHG",
        "IUSG",
        "ILCG",
        "CFA",
    ],
    "US_Value_Large": [
        "VTV",
        "IWD",
        "SCHV",
        "VONV",
        "MGV",
        "IVE",
        "SPYV",
        "VYK",
        "JKF",
        "VLUE",
        "IWW",
        "IUSV",
        "IWX",
        "ILCV",
        "CFO",
    ],
    "US_Growth_Mid": [
        "VOT",
        "IJK",
        "SCHM",
        "IMCG",
        "JKH",
        "MDYG",
        "VBK",
    ],
    "US_Value_Mid": [
        "VOE",
        "IJJ",
        "MDYV",
        "IMCV",
        "JKI",
        "VBR",
    ],
    "US_Growth_Small": [
        "VBK",
        "IWO",
        "SLYG",
        "VIOG",
        "IJT",
        "JKK",
    ],
    "US_Value_Small": [
        "VBR",
        "IWN",
        "SLYV",
        "VIOV",
        "IJS",
        "JKL",
    ],
    # ======================================================================
    # US EQUITY - SECTORS (150+ ETFs)
    # ======================================================================
    "Sector_Technology": [
        "XLK",
        "VGT",
        "FTEC",
        "IGV",
        "SMH",
        "SOXX",
        "PSI",
        "XSD",
        "IGN",
        "QTEC",
        "VONG",
        "TECL",
        "FDN",
        "SKYY",
        "CLOU",
        "HACK",
        "CIBR",
        "BUG",
        "WCLD",
        "IGV",
        "VGT",
        "IYW",
        "SRVR",
        "ARKF",
        "FINX",
        "FITE",
        "IPAY",
        "FDNI",
    ],
    "Sector_Healthcare": [
        "XLV",
        "VHT",
        "IYH",
        "FHLC",
        "IBB",
        "XBI",
        "IHI",
        "IHE",
        "BBH",
        "XHS",
        "IHF",
        "VHT",
        "GNOM",
        "ARKG",
        "IDNA",
        "PJP",
        "PTH",
        "SBIO",
        "XPH",
        "BBP",
    ],
    "Sector_Financials": [
        "XLF",
        "VFH",
        "IYF",
        "FNCL",
        "KRE",
        "KBE",
        "IAI",
        "KBWB",
        "IAT",
        "FXO",
        "KCE",
        "KIE",
        "PSCF",
        "FAS",
        "RYF",
        "IYG",
        "KBWP",
        "KBWR",
        "KBWY",
        "BDCX",
    ],
    "Sector_Energy": [
        "XLE",
        "VDE",
        "IYE",
        "FENY",
        "IEO",
        "PXE",
        "XES",
        "OIH",
        "AMLP",
        "IEZ",
        "PXI",
        "PBW",
        "TAN",
        "FAN",
        "ICLN",
        "QCLN",
        "SMOG",
        "ACES",
        "CNRG",
        "PBD",
    ],
    "Sector_Consumer_Discretionary": [
        "XLY",
        "VCR",
        "IYC",
        "FDIS",
        "RTH",
        "XRT",
        "PEJ",
        "FXD",
        "IYK",
        "RSPD",
        "PSCD",
        "VPC",
        "FBT",
        "WANT",
    ],
    "Sector_Consumer_Staples": [
        "XLP",
        "VDC",
        "IYK",
        "FSTA",
        "KXI",
        "FXG",
        "PBJ",
        "PSCC",
        "RSPS",
        "VPC",
    ],
    "Sector_Industrials": [
        "XLI",
        "VIS",
        "IYJ",
        "FIDU",
        "IYT",
        "XTN",
        "PPA",
        "FXR",
        "PAVE",
        "CARZ",
        "RSPI",
        "PSCI",
        "ITA",
        "PBS",
    ],
    "Sector_Materials": [
        "XLB",
        "VAW",
        "IYM",
        "FMAT",
        "XME",
        "PICK",
        "REMX",
        "LIT",
        "SLX",
        "MXI",
        "RTM",
        "MOO",
    ],
    "Sector_Real_Estate": [
        "VNQ",
        "IYR",
        "XLRE",
        "SCHH",
        "RWR",
        "USRT",
        "REET",
        "ICF",
        "RWO",
        "BBRE",
        "FREL",
        "PSR",
        "HOMZ",
        "ROOF",
        "INDS",
    ],
    "Sector_Utilities": [
        "XLU",
        "VPU",
        "IDU",
        "FUTY",
        "RYU",
        "PUI",
        "RSPU",
    ],
    "Sector_Communication": [
        "XLC",
        "VOX",
        "IYZ",
        "FCOM",
        "RSPC",
    ],
    # ======================================================================
    # INTERNATIONAL DEVELOPED MARKETS (150+ ETFs)
    # ======================================================================
    "Intl_Broad_Developed": [
        "VEA",
        "IEFA",
        "EFA",
        "SCHF",
        "IXUS",
        "VEU",
        "VXUS",
        "IDEV",
        "ACWI",
        "ACWX",
        "URTH",
        "IOO",
        "INTF",
        "CWI",
        "DFAI",
        "DFIV",
        "AVDV",
        "EFAA",
        "DINT",
    ],
    "Intl_Europe": [
        "VGK",
        "EZU",
        "FEZ",
        "IEV",
        "IEUR",
        "HEDJ",
        "HEZU",
        "EWU",
        "EWG",
        "EWQ",
        "EWP",
        "EWI",
        "EWK",
        "EWL",
        "EWN",
        "EWD",
        "EWO",
        "EWS",
        "DBEU",
        "SPEU",
        "FGM",
    ],
    "Intl_Asia_Pacific": [
        "AAXJ",
        "AIA",
        "EPP",
        "GMF",
        "DFE",
        "EWJ",
        "DXJ",
        "HEWJ",
        "EWY",
        "EWA",
        "EWT",
        "EWH",
        "EWS",
        "EWM",
        "EWI",
        "EIDO",
        "EWS",
        "EPHE",
        "THD",
        "INDA",
        "INDY",
        "PIN",
    ],
    "Intl_Single_Country": [
        "EWJ",
        "EWG",
        "EWU",
        "EWC",
        "EWA",
        "EWH",
        "EWT",
        "EWY",
        "EWZ",
        "EWW",
        "EWI",
        "EWQ",
        "EWP",
        "EWL",
        "EWK",
        "EWD",
        "EWS",
        "EWM",
        "INDA",
        "MCHI",
        "FXI",
        "GXG",
        "NORW",
        "EZA",
        "EWN",
        "EPOL",
        "EPHE",
        "THD",
        "EDEN",
        "ENZL",
        "ARGT",
        "ECH",
        "EPU",
        "GREK",
        "RSX",
        "ERUS",
        "TUR",
    ],
    "Intl_Developed_SmallCap": [
        "VSS",
        "SCZ",
        "DLS",
        "FNDC",
        "AVDS",
        "DIM",
        "IFSM",
    ],
    # ======================================================================
    # EMERGING MARKETS (100+ ETFs)
    # ======================================================================
    "Emerging_Broad": [
        "VWO",
        "EEM",
        "IEMG",
        "SCHE",
        "SPEM",
        "DEM",
        "EMGF",
        "EEMD",
        "EEMV",
        "GEM",
        "EDC",
        "DGS",
        "DFEM",
        "DFEV",
        "FNDE",
        "XMMO",
        "PIE",
        "DVEM",
    ],
    "Emerging_Asia": [
        "VWO",
        "AAXJ",
        "EEM",
        "GMF",
        "DEM",
        "MCHI",
        "FXI",
        "GXC",
        "YINN",
        "KWEB",
        "CQQQ",
        "ASHR",
        "CN",
        "CHIQ",
        "CXSE",
        "ECNS",
        "PGJ",
    ],
    "Emerging_Latin_America": [
        "ILF",
        "EWZ",
        "EWW",
        "ARGT",
        "ECH",
        "EPU",
        "FLAX",
        "EWZS",
        "UBR",
    ],
    "Emerging_EMEA": [
        "EMEA",
        "GAF",
        "AFK",
        "NGE",
        "RSX",
        "ERUS",
        "TUR",
        "FM",
        "GULF",
        "MENA",
        "EZA",
    ],
    "Emerging_SmallCap": [
        "EWX",
        "EEMS",
        "DGS",
        "GMM",
    ],
    # ======================================================================
    # FIXED INCOME - US (200+ ETFs)
    # ======================================================================
    "Bonds_Aggregate": [
        "AGG",
        "BND",
        "SCHZ",
        "IUSB",
        "FBND",
        "BOND",
        "EAGG",
        "BNDC",
        "USIG",
        "SPAB",
        "BIV",
        "TOTL",
    ],
    "Bonds_Treasury": [
        "IEF",
        "SHY",
        "TLT",
        "IEI",
        "SHV",
        "VGSH",
        "VGIT",
        "VGLT",
        "SCHO",
        "SCHR",
        "SPTS",
        "SPTL",
        "GOVT",
        "VTES",
        "BSV",
        "BIV",
        "BLV",
        "EDV",
        "ZROZ",
        "TMF",
        "TMV",
    ],
    "Bonds_Corporate": [
        "LQD",
        "VCIT",
        "VCLT",
        "VCSH",
        "IGIB",
        "USIG",
        "CORP",
        "IG",
        "VCLT",
        "SPLB",
        "IGIB",
        "SLQD",
        "SCHI",
        "NEAR",
        "ICSH",
        "FLCO",
        "FLOT",
        "FLTR",
        "SCHO",
        "GSY",
        "MINT",
    ],
    "Bonds_High_Yield": [
        "HYG",
        "JNK",
        "USHY",
        "ANGL",
        "SJNK",
        "SHYG",
        "HYDB",
        "PHB",
        "HYLB",
        "HYGV",
        "HYDW",
        "HYXU",
        "SRLN",
        "BSJN",
        "HYGH",
        "HYLS",
        "FALN",
        "HYZD",
    ],
    "Bonds_Municipal": [
        "MUB",
        "VTEB",
        "TFI",
        "SMB",
        "SHM",
        "ITM",
        "HYD",
        "SUB",
        "PVI",
        "PWZ",
        "PZA",
        "BAB",
        "IBMK",
        "IBMJ",
        "IBMH",
        "IBMI",
        "IBMN",
        "MUST",
        "MMIN",
        "MMIT",
    ],
    "Bonds_TIPS": [
        "TIP",
        "VTIP",
        "SCHP",
        "IPE",
        "SPIP",
        "TDTT",
        "LTPZ",
        "STPZ",
        "TIPX",
        "GTIP",
    ],
    "Bonds_International": [
        "BNDX",
        "IAGG",
        "IGOV",
        "BWX",
        "ISHG",
        "PICB",
        "VWOB",
        "EMB",
        "PCY",
        "EMLC",
        "EBND",
        "LEMB",
        "EMHY",
        "HYEM",
        "ELD",
        "EMAG",
        "EMCR",
        "EMSH",
        "EMTL",
    ],
    "Bonds_Floating_Rate": [
        "FLOT",
        "FLRN",
        "FLTR",
        "TFLO",
        "USFR",
        "ICSH",
        "JPST",
        "FLRT",
    ],
    "Bonds_Preferred": [
        "PFF",
        "PGX",
        "PGF",
        "FPE",
        "PSK",
        "PFXF",
        "PUI",
        "PFFA",
        "PFFR",
        "PFFV",
    ],
    # ======================================================================
    # COMMODITIES & REAL ASSETS (80+ ETFs)
    # ======================================================================
    "Commodities_Broad": [
        "DBC",
        "GSG",
        "DJP",
        "PDBC",
        "COMT",
        "GCC",
        "BCD",
        "BCI",
    ],
    "Commodities_Gold": [
        "GLD",
        "IAU",
        "SGOL",
        "GLDM",
        "BAR",
        "AAAU",
        "OUNZ",
        "IAUM",
        "TGLD",
        "FG",
        "UGL",
    ],
    "Commodities_Silver": [
        "SLV",
        "SIVR",
        "SLVP",
        "AGQ",
    ],
    "Commodities_Metals": [
        "GDX",
        "GDXJ",
        "SIL",
        "COPX",
        "PICK",
        "REMX",
        "LIT",
        "DBB",
        "PPLT",
        "PALL",
        "XME",
        "CPER",
    ],
    "Commodities_Energy": [
        "USO",
        "UNG",
        "BNO",
        "UGA",
        "OIL",
        "DBO",
        "DBE",
        "NRGI",
    ],
    "Commodities_Agriculture": [
        "DBA",
        "CORN",
        "WEAT",
        "SOYB",
        "COW",
        "CANE",
        "MOO",
        "VEGI",
    ],
    # ======================================================================
    # DIVIDEND & INCOME (80+ ETFs)
    # ======================================================================
    "Dividend_High_Yield": [
        "VYM",
        "DVY",
        "SDY",
        "HDV",
        "VIG",
        "SCHD",
        "NOBL",
        "DGRO",
        "FVD",
        "SPHD",
        "IDV",
        "DHS",
        "DON",
        "DES",
        "DFE",
        "DTN",
        "DTH",
        "DEM",
        "KBWD",
        "WDIV",
        "DIV",
        "DLN",
        "DWX",
    ],
    "Dividend_Growth": [
        "VIG",
        "SCHD",
        "DGRO",
        "NOBL",
        "DGRW",
        "RDVY",
        "SDY",
        "FVD",
        "VYM",
        "DGRS",
        "DTD",
    ],
    "Dividend_International": [
        "VYMI",
        "IDV",
        "SCHY",
        "DWX",
        "IQDY",
        "DTH",
        "DHS",
        "DON",
        "DES",
        "DFE",
        "DTN",
        "DEM",
        "DVYE",
        "PDI",
    ],
    # ======================================================================
    # SMART BETA & FACTOR (100+ ETFs)
    # ======================================================================
    "Factor_Quality": [
        "QUAL",
        "JQUA",
        "SPHQ",
        "DUHP",
        "IQLT",
        "JQUAL",
        "QLTA",
        "OUSA",
    ],
    "Factor_Low_Volatility": [
        "USMV",
        "SPLV",
        "XMLV",
        "EFAV",
        "EEMV",
        "ACWV",
        "LVHD",
        "LGLV",
        "SPHD",
        "FDVV",
        "FDLO",
    ],
    "Factor_Momentum": [
        "MTUM",
        "PDP",
        "SPMO",
        "MMTM",
        "IMOM",
        "JMOM",
        "FDMO",
        "XMMO",
        "QMOM",
        "FTXL",
        "VFMF",
        "PTNQ",
    ],
    "Factor_Value": [
        "VLUE",
        "IVE",
        "VTV",
        "RPV",
        "VOOV",
        "IWD",
        "SPYV",
        "FVAL",
        "JVAL",
        "IVAL",
        "OUSV",
        "SLYV",
        "JHMV",
    ],
    "Factor_Size": [
        "SIZE",
        "IJR",
        "IWM",
        "VB",
        "SCHA",
        "VIOO",
        "PRFZ",
    ],
    "Factor_Multi": [
        "LRGF",
        "INTF",
        "DFUS",
        "DFAS",
        "DFAI",
        "DFIV",
        "AVUS",
        "AVUV",
        "DFAX",
        "AVDV",
        "AVDE",
        "DFAE",
        "DFEQ",
    ],
    # ======================================================================
    # THEMATIC & INNOVATIVE (100+ ETFs)
    # ======================================================================
    "Thematic_Technology": [
        "ARKK",
        "ARKQ",
        "ARKW",
        "ARKG",
        "ARKF",
        "MOON",
        "ROBO",
        "BOTZ",
        "AIQ",
        "AIEQ",
        "SNSR",
        "CLOU",
        "SKYY",
        "HACK",
        "CIBR",
        "BUG",
        "IPAY",
        "FINX",
        "FITE",
        "GBTC",
        "BITO",
        "BITI",
    ],
    "Thematic_Clean_Energy": [
        "ICLN",
        "TAN",
        "FAN",
        "QCLN",
        "PBW",
        "ACES",
        "SMOG",
        "CNRG",
        "PBD",
        "CTEC",
        "GRID",
        "RAYS",
    ],
    "Thematic_Electric_Vehicles": [
        "DRIV",
        "IDRV",
        "KARS",
        "HAIL",
        "CARZ",
        "LIT",
    ],
    "Thematic_Gaming": [
        "ESPO",
        "HERO",
        "GAMR",
        "NERD",
        "BJK",
    ],
    "Thematic_Cannabis": [
        "MJ",
        "YOLO",
        "MSOS",
        "THCX",
        "CNBS",
        "TOKE",
        "POTX",
    ],
    "Thematic_Space": [
        "UFO",
        "ROKT",
        "ARKX",
    ],
    "Thematic_Infrastructure": [
        "PAVE",
        "IFRA",
        "NFRA",
        "IGF",
        "PKB",
    ],
    "Thematic_Home_Construction": [
        "ITB",
        "XHB",
        "HOMZ",
        "PKB",
    ],
    # ======================================================================
    # ESG & SUSTAINABLE (60+ ETFs)
    # ======================================================================
    "ESG_Broad": [
        "ESGU",
        "ESGV",
        "SUSL",
        "DSI",
        "USSG",
        "SUSA",
        "ESGE",
        "EAGG",
        "SUSC",
        "ESGD",
        "XT",
        "KRMA",
        "VOTE",
        "VETS",
        "DEMZ",
        "CHGX",
        "VSGX",
        "ESGE",
    ],
    "ESG_Thematic": [
        "SHE",
        "PAVE",
        "WOMN",
        "BIBL",
        "BLES",
        "PRAY",
        "VICE",
    ],
    # ======================================================================
    # CURRENCY & ALTERNATIVE (60+ ETFs)
    # ======================================================================
    "Currency": [
        "UUP",
        "FXE",
        "FXY",
        "FXC",
        "FXA",
        "FXB",
        "FXF",
        "CYB",
        "CEW",
        "DBV",
        "UDN",
        "USDU",
    ],
    "Volatility": [
        "VXX",
        "VIXY",
        "UVXY",
        "SVXY",
        "TAIL",
        "VXZ",
    ],
    "Alternative_Strategies": [
        "QAI",
        "BTAL",
        "MNA",
        "FTLS",
        "CTA",
        "KMLM",
        "DBMF",
        "CLIX",
        "IEO",
        "SWAN",
        "NUSI",
        "QYLD",
        "RYLD",
        "JEPI",
        "DIVO",
    ],
    # ======================================================================
    # MULTI-ASSET & ALLOCATION (40+ ETFs)
    # ======================================================================
    "MultiAsset_Conservative": [
        "AOK",
        "AOM",
        "AOR",
        "AOA",
        "GAL",
        "IYLD",
    ],
    "MultiAsset_Moderate": [
        "AOR",
        "GAL",
        "AOM",
    ],
    "MultiAsset_Aggressive": [
        "AOA",
        "PDBC",
        "RPAR",
    ],
    "Target_Date": [
        "TDV",
        "TDF",
        "TDIV",
        "AADR",
        "GLDX",
    ],
    # ======================================================================
    # LEVERAGED & INVERSE (for future strategies — filtered from basic model)
    # ======================================================================
    "Leveraged_Bull_2x": [
        "SSO", "DDM", "MVV", "UGL", "AGQ", "UCO", "UYG", "URE",
        "UCC", "UYM", "UGE", "UPW", "UJB", "SAA", "UKK", "UPV",
        "UXI", "UKF", "UJO",
    ],
    "Leveraged_Bull_3x": [
        "TECL", "TQQQ", "SOXL", "UPRO", "UDOW", "URTY", "FAS",
        "TNA", "CURE", "WANT", "BULZ", "PILL", "NUGT", "JNUG",
        "MIDU", "ERX", "TMF", "TYD", "BOIL", "LABU", "YINN",
    ],
    "Leveraged_Bear_2x": [
        "SKK", "SZK", "SMN", "SDD", "SDK", "SDP", "SRS", "TWM",
        "SBB", "DXD", "MZZ", "PST", "TBT", "TBF", "SSG",
    ],
    "Leveraged_Bear_3x": [
        "SQQQ", "SPXU", "SDOW", "SRTY", "FAZ", "TZA", "SOXS",
        "TMV", "ERY", "KOLD", "SPXS", "YANG", "LABD", "DRV", "EDZ",
    ],
    "Volatility_Products": [
        "UVXY", "SVXY", "VXX", "VIXY",
    ],
}


def get_all_tickers():
    """Get flat list of all tickers from the curated list."""
    all_tickers = set()
    for category, tickers in COMPREHENSIVE_ETF_UNIVERSE.items():
        all_tickers.update(tickers)
    return sorted(list(all_tickers))


def get_tickers_by_category(category_name):
    """Get tickers for a specific category"""
    return COMPREHENSIVE_ETF_UNIVERSE.get(category_name, [])


def get_categories():
    """Get list of all categories"""
    return list(COMPREHENSIVE_ETF_UNIVERSE.keys())


def load_full_universe(nasdaq_file=None):
    """Load the full US ETF universe from the NASDAQ trader file.

    Merges the official NASDAQ ETF list (~4,900+ tickers) with our
    curated categorised list. Returns (all_tickers, categories_map).

    Parameters
    ----------
    nasdaq_file : str or Path, optional
        Path to nasdaq_etf_universe.txt.  Defaults to
        data/raw/nasdaq_etf_universe.txt relative to the project root.

    Returns
    -------
    all_tickers : list[str]
        Sorted list of all unique ETF tickers.
    categories_map : dict[str, str]
        Mapping of ticker -> category (from curated list).
        Tickers only in the NASDAQ file get category "Uncategorized".
    """
    from pathlib import Path as _Path

    # Build category map from curated list
    categories_map = {}
    for cat, tickers in COMPREHENSIVE_ETF_UNIVERSE.items():
        for t in tickers:
            categories_map[t] = cat

    curated = set(categories_map.keys())

    # Locate NASDAQ file
    if nasdaq_file is None:
        # Try common locations relative to this file and project root
        here = _Path(__file__).resolve().parent
        candidates = [
            here.parent.parent / "data" / "raw" / "nasdaq_etf_universe.txt",
            _Path.cwd() / "data" / "raw" / "nasdaq_etf_universe.txt",
            _Path.cwd().parent / "data" / "raw" / "nasdaq_etf_universe.txt",
        ]
        for c in candidates:
            if c.exists():
                nasdaq_file = c
                break

    nasdaq_tickers = set()
    if nasdaq_file and _Path(nasdaq_file).exists():
        with open(nasdaq_file) as f:
            for line in f:
                t = line.strip()
                if t:
                    nasdaq_tickers.add(t)

    # Assign "Uncategorized" to NASDAQ-only tickers
    for t in nasdaq_tickers:
        if t not in categories_map:
            categories_map[t] = "Uncategorized"

    all_tickers = sorted(curated | nasdaq_tickers)
    return all_tickers, categories_map


if __name__ == "__main__":
    all_tickers = get_all_tickers()
    print(f"Curated ETFs: {len(all_tickers)}")
    print(f"Categories: {len(get_categories())}")

    full, cats = load_full_universe()
    curated_only = sum(1 for t in full if cats[t] != "Uncategorized")
    print(f"\nFull universe: {len(full)} ETFs "
          f"({curated_only} categorized, {len(full) - curated_only} uncategorized)")
    print(f"\nSample categories:")
    for cat in list(COMPREHENSIVE_ETF_UNIVERSE.keys())[:10]:
        count = len(COMPREHENSIVE_ETF_UNIVERSE[cat])
        print(f"  {cat:40s}: {count:3d} ETFs")
