"""Add cash column to portfolios

Revision ID: 028b89f1c85f
Revises:
Create Date: 2025-10-10 17:38:32.215778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028b89f1c85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then update values, then make NOT NULL
    op.add_column('portfolios', sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=True))

    # Set cash to initial_capital for existing portfolios
    op.execute('UPDATE portfolios SET cash = initial_capital WHERE cash IS NULL')

    # Now make it NOT NULL
    op.alter_column('portfolios', 'cash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'cash')
    # ### end Alembic commands ###
